; =========================================================
; CONFIGURACIÓN PIPELINE COMPLETO
; =========================================================

[ARCHIVOS]
excel_precios        = C:\Users\andres.hernandez\OneDrive - IMECOL S.A.S\Documentos\PRUEBA PI PRECIOS\Lista de precios CNH Consolidadas Vigente.xlsx
excel_disponibilidad = C:\Users\andres.hernandez\OneDrive - IMECOL S.A.S\Documentos\PRUEBA PI PRECIOS\Lista Disponibilidad Origen.xlsx
excel_lista          = C:\Users\andres.hernandez\OneDrive - IMECOL S.A.S\Documentos\PRUEBA PI PRECIOS\Precios De Lista_Prueba.xlsx

[SALIDA]
duckdb       = pipeline.duckdb
csv          = precios_consolidados.csv
excel_salida = Precio_De_Lista_con_Precios.xlsx

[SQLSERVER]
server   = 10.75.71.10,1433
database = UnoEE
db_user  = ahernandez
db_pass  = "1gUC?\5/Eim"

[FACTORES]
factor_br  = 1.25
factor_usa = 1.25
factor_eur = 1.5

[TABLAS]
table_items         = items_referencias
table_items_precios = items_referencias_con_precios
[SALIDA_VENTAS]
excel = ventas_precios_cnh.xlsx
csv   = ventas_precios_cnh.csv
